config:
  data:
    batch_size: 96
    image_size: 224
    num_workers: 4
    shuffle: true
    test_path: ../../src/data/scaled-bilinear/test
    training_path: ../../src/data/scaled-bilinear/train
    validation_path: ../../src/data/scaled-bilinear/validation
  experiment_name: sampled_efficientnet_b0_scaledbilinear_jt
  logging:
    checkpoint_dir: checkpoints
    logs_dir: logs
    type: CSV
  model:
    name: efficientnet_b0
    num_classes: 2
    pretrained: true
  seed: 7643
  training:
    early_stopping:
      enabled: true
      mode: min
      monitor: val_loss
      patience: 3
    learning_rate: 3e-5
    lr_monitoring: true
    max_epochs: 10
    min_epochs: 5
    optimizer_type: adamw
    weight_decay: 5e-4
